server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_advanced
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select u.email, r.role from users u inner join user_roles ur on(u.user_id=ur.user_id) inner join roles r on(ur.role_id=r.role_id) where u.email=?
